FORMS += androtouchwidget.ui
HEADERS += androtouch.h
SOURCES += androtouch.cpp main.cpp
RESOURCES += androtouch.qrc
ANDROTOUCH = app
CONFIG += release warn_on thread qt
TARGET = androtouch
QT += widgets network
RC_FILE = androtouch.rc
